---
title: "COVID-19 in Panama"
description: After the confirmation by the World Health Organization (WHO) with a novel coronavirus which caused a respiratory illness in a cluster of people in Wuhan City, Hubei Province, China, COVID-19 became to spread in various of countries, including Panama. 

  
author:
  - name: Lulu Pi 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 18-09-2020
bibliography: references.bib
output:
  distill::distill_article:
    self_contained: false
    citation_package: biblatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(rmarkdown)
library(readr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(kableExtra)
library(ggrepel)
library(hrbrthemes)
library(plotly)
library(gridExtra)

```

```{r clean_data}
confirmed <- read_csv("covid19_confirmed_global.csv") %>%
  filter(`Country/Region` == "Panama") %>%
  pivot_longer(cols = "1/22/20":"9/16/20",
               names_to = "Date",
               values_to = "Confirmed") %>%
  select(Date, Confirmed) 
  
  
deaths <- read_csv("covid19_deaths_global.csv") %>%
  filter(`Country/Region` == "Panama") %>%
  pivot_longer(cols = "1/22/20":"9/16/20",
               names_to = "Date",
               values_to = "Deaths") %>%
  select("Date", "Deaths")

recovered <- read_csv("covid19_recovered_global.csv") %>%
  filter(`Country/Region` == "Panama") %>%
  pivot_longer(cols = "1/22/20":"9/16/20",
               names_to = "Date",
               values_to = "Recovered") %>%
  select("Date", "Recovered")

Panama_covid19 <- confirmed %>%
  left_join(deaths,
            by = "Date") %>%
  left_join(recovered,
            by = "Date") %>%
  mutate(Month = substr(confirmed$Date, start = 1, stop = 1)) 

Panama_month <- Panama_covid19 %>%
  group_by(Month) %>%
  summarise(Confirmed = sum(Confirmed),
            Deaths = sum(Deaths),
            Recovered = sum(Recovered))
kable(Panama_month, caption = "COn 12 January 2020, the World Health Organization (WHO) confirmed that a novel coronavirus was the cause of a respiratory illness in a cluster of people in Wuhan City, Hubei Province, China,ases of COVID-19 in Panama per month") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r Panama_longer_Month}
Panama_longer <- Panama_covid19 %>%
  
pivot_longer(cols = c("Confirmed",
                      "Deaths",
                      "Recovered"),
             names_to = "Type",
             values_to = "Cases") 

```

```{r geom_bar_Panama}
Panama_longer %>%
  group_by(Month,
           Type) %>%
  summarise(Cases = sum(Cases)) %>%
  ggplot(aes(fill = Type,
           y = Cases,
           x = Month,
           label = Cases)) +
  geom_bar(position="dodge", 
           stat="identity") +
  theme_bw() +
  ggtitle("COVID-19 cases in Panama per month") +
  theme(plot.title = element_text(size = 25,
                                  color = "blue"),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        legend.title = element_text(size = 15)) +
  geom_text_repel()


```
```{r}
g1 <- ggplot(Panama_covid19,
             aes(x = Date,
                 y = Confirmed,
                 group = Month)) +
  geom_line(color = "red") +
  theme(axis.text.x = element_blank(),
        axis.title.y = element_text(size = 10,
                                    color = "red"),
        axis.ticks = element_blank()) +
  xlab(" ") +
  ggtitle("trend of COVID-19 cases in Panama as of 16 September 2020")
g2 <- ggplot(Panama_covid19,
             aes(x = Date,
                 y = Deaths,
                 group = Month)) +
  geom_line(color = "green") +
  theme(axis.text.x = element_blank(),
        axis.title.y = element_text(size = 10,
                                    color = "green"),
        axis.ticks = element_blank()) +
  xlab(" ")
g3 <- ggplot(Panama_covid19,
             aes(x = Date,
                 y = Recovered,
                 group = Month)) +
  geom_line(color = "blue") +
  theme(axis.text.x = element_blank(),
        axis.title.y = element_text(size = 10,
                                    color = "blue"),
        axis.ticks = element_blank()) +
  xlab("Date")

grid.arrange(g1, g2, g3)
```




```{r interact_point}
p <- ggplot(Panama_longer,
            aes(x = Month, 
           y = Cases, 
           text = Date,
           color= Type)) + 
  geom_point() +  
  facet_wrap(~Type , dir="v")  +
  theme(legend.position="none",
        aspect.ratio = 1) +
   ggtitle("COVID-19 cases in Panama each day as of 16 September 2020") +
  theme(plot.title = element_text(color = "blue"),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15)) +
  xlab("Month") +
  ylab("Cases")
  
ggplotly(p)
```

















